/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAssinaturasRouteImport } from './routes/admin-assinaturas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as IaRouteImport } from './routes/ia'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as MaterialRouteImport } from './routes/material'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MinhaAssinaturaRouteImport } from './routes/minha-assinatura'
import { Route as OsceRouteImport } from './routes/osce'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PremiumCanceladoRouteImport } from './routes/premium-cancelado'
import { Route as PremiumPendenteRouteImport } from './routes/premium-pendente'
import { Route as PremiumSucessoRouteImport } from './routes/premium-sucesso'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as SimuladosRouteImport } from './routes/simulados'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicClassificacaoProcessarRouteImport } from './routes/api/public/classificacao/processar'
import { Route as ApiPublicMigracaoTaxonomiaProcessarRouteImport } from './routes/api/public/migracao-taxonomia/processar'
import { Route as ApiPublicReclassificacaoProcessarRouteImport } from './routes/api/public/reclassificacao/processar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssinaturasRoute = AdminAssinaturasRouteImport.update({
  id: '/admin-assinaturas',
  path: '/admin-assinaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialRoute = MaterialRouteImport.update({
  id: '/material',
  path: '/material',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAssinaturaRoute = MinhaAssinaturaRouteImport.update({
  id: '/minha-assinatura',
  path: '/minha-assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const OsceRoute = OsceRouteImport.update({
  id: '/osce',
  path: '/osce',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumCanceladoRoute = PremiumCanceladoRouteImport.update({
  id: '/premium-cancelado',
  path: '/premium-cancelado',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumPendenteRoute = PremiumPendenteRouteImport.update({
  id: '/premium-pendente',
  path: '/premium-pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSucessoRoute = PremiumSucessoRouteImport.update({
  id: '/premium-sucesso',
  path: '/premium-sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosRoute = SimuladosRouteImport.update({
  id: '/simulados',
  path: '/simulados',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClassificacaoProcessarRoute =
  ApiPublicClassificacaoProcessarRouteImport.update({
    id: '/api/public/classificacao/processar',
    path: '/api/public/classificacao/processar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMigracaoTaxonomiaProcessarRoute =
  ApiPublicMigracaoTaxonomiaProcessarRouteImport.update({
    id: '/api/public/migracao-taxonomia/processar',
    path: '/api/public/migracao-taxonomia/processar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReclassificacaoProcessarRoute =
  ApiPublicReclassificacaoProcessarRouteImport.update({
    id: '/api/public/reclassificacao/processar',
    path: '/api/public/reclassificacao/processar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-assinaturas': typeof AdminAssinaturasRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipes': typeof EquipesRoute
  '/flashcards': typeof FlashcardsRoute
  '/ia': typeof IaRoute
  '/importar': typeof ImportarRoute
  '/ligas': typeof LigasRoute
  '/material': typeof MaterialRoute
  '/mcp': typeof McpRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/osce': typeof OsceRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/premium-cancelado': typeof PremiumCanceladoRoute
  '/premium-pendente': typeof PremiumPendenteRoute
  '/premium-sucesso': typeof PremiumSucessoRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/simulados': typeof SimuladosRoute
  '/suporte': typeof SuporteRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/classificacao/processar': typeof ApiPublicClassificacaoProcessarRoute
  '/api/public/migracao-taxonomia/processar': typeof ApiPublicMigracaoTaxonomiaProcessarRoute
  '/api/public/reclassificacao/processar': typeof ApiPublicReclassificacaoProcessarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-assinaturas': typeof AdminAssinaturasRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipes': typeof EquipesRoute
  '/flashcards': typeof FlashcardsRoute
  '/ia': typeof IaRoute
  '/importar': typeof ImportarRoute
  '/ligas': typeof LigasRoute
  '/material': typeof MaterialRoute
  '/mcp': typeof McpRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/osce': typeof OsceRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/premium-cancelado': typeof PremiumCanceladoRoute
  '/premium-pendente': typeof PremiumPendenteRoute
  '/premium-sucesso': typeof PremiumSucessoRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/simulados': typeof SimuladosRoute
  '/suporte': typeof SuporteRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/classificacao/processar': typeof ApiPublicClassificacaoProcessarRoute
  '/api/public/migracao-taxonomia/processar': typeof ApiPublicMigracaoTaxonomiaProcessarRoute
  '/api/public/reclassificacao/processar': typeof ApiPublicReclassificacaoProcessarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-assinaturas': typeof AdminAssinaturasRoute
  '/auth': typeof AuthRoute
  '/cronograma': typeof CronogramaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/equipes': typeof EquipesRoute
  '/flashcards': typeof FlashcardsRoute
  '/ia': typeof IaRoute
  '/importar': typeof ImportarRoute
  '/ligas': typeof LigasRoute
  '/material': typeof MaterialRoute
  '/mcp': typeof McpRoute
  '/minha-assinatura': typeof MinhaAssinaturaRoute
  '/osce': typeof OsceRoute
  '/perfil': typeof PerfilRoute
  '/premium': typeof PremiumRoute
  '/premium-cancelado': typeof PremiumCanceladoRoute
  '/premium-pendente': typeof PremiumPendenteRoute
  '/premium-sucesso': typeof PremiumSucessoRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/simulados': typeof SimuladosRoute
  '/suporte': typeof SuporteRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/classificacao/processar': typeof ApiPublicClassificacaoProcessarRoute
  '/api/public/migracao-taxonomia/processar': typeof ApiPublicMigracaoTaxonomiaProcessarRoute
  '/api/public/reclassificacao/processar': typeof ApiPublicReclassificacaoProcessarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-assinaturas'
    | '/auth'
    | '/cronograma'
    | '/diagnostico'
    | '/equipes'
    | '/flashcards'
    | '/ia'
    | '/importar'
    | '/ligas'
    | '/material'
    | '/mcp'
    | '/minha-assinatura'
    | '/osce'
    | '/perfil'
    | '/premium'
    | '/premium-cancelado'
    | '/premium-pendente'
    | '/premium-sucesso'
    | '/questoes'
    | '/ranking'
    | '/simulados'
    | '/suporte'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/classificacao/processar'
    | '/api/public/migracao-taxonomia/processar'
    | '/api/public/reclassificacao/processar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-assinaturas'
    | '/auth'
    | '/cronograma'
    | '/diagnostico'
    | '/equipes'
    | '/flashcards'
    | '/ia'
    | '/importar'
    | '/ligas'
    | '/material'
    | '/mcp'
    | '/minha-assinatura'
    | '/osce'
    | '/perfil'
    | '/premium'
    | '/premium-cancelado'
    | '/premium-pendente'
    | '/premium-sucesso'
    | '/questoes'
    | '/ranking'
    | '/simulados'
    | '/suporte'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/classificacao/processar'
    | '/api/public/migracao-taxonomia/processar'
    | '/api/public/reclassificacao/processar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-assinaturas'
    | '/auth'
    | '/cronograma'
    | '/diagnostico'
    | '/equipes'
    | '/flashcards'
    | '/ia'
    | '/importar'
    | '/ligas'
    | '/material'
    | '/mcp'
    | '/minha-assinatura'
    | '/osce'
    | '/perfil'
    | '/premium'
    | '/premium-cancelado'
    | '/premium-pendente'
    | '/premium-sucesso'
    | '/questoes'
    | '/ranking'
    | '/simulados'
    | '/suporte'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/classificacao/processar'
    | '/api/public/migracao-taxonomia/processar'
    | '/api/public/reclassificacao/processar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminAssinaturasRoute: typeof AdminAssinaturasRoute
  AuthRoute: typeof AuthRoute
  CronogramaRoute: typeof CronogramaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EquipesRoute: typeof EquipesRoute
  FlashcardsRoute: typeof FlashcardsRoute
  IaRoute: typeof IaRoute
  ImportarRoute: typeof ImportarRoute
  LigasRoute: typeof LigasRoute
  MaterialRoute: typeof MaterialRoute
  McpRoute: typeof McpRoute
  MinhaAssinaturaRoute: typeof MinhaAssinaturaRoute
  OsceRoute: typeof OsceRoute
  PerfilRoute: typeof PerfilRoute
  PremiumRoute: typeof PremiumRoute
  PremiumCanceladoRoute: typeof PremiumCanceladoRoute
  PremiumPendenteRoute: typeof PremiumPendenteRoute
  PremiumSucessoRoute: typeof PremiumSucessoRoute
  QuestoesRoute: typeof QuestoesRoute
  RankingRoute: typeof RankingRoute
  SimuladosRoute: typeof SimuladosRoute
  SuporteRoute: typeof SuporteRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicClassificacaoProcessarRoute: typeof ApiPublicClassificacaoProcessarRoute
  ApiPublicMigracaoTaxonomiaProcessarRoute: typeof ApiPublicMigracaoTaxonomiaProcessarRoute
  ApiPublicReclassificacaoProcessarRoute: typeof ApiPublicReclassificacaoProcessarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-assinaturas': {
      id: '/admin-assinaturas'
      path: '/admin-assinaturas'
      fullPath: '/admin-assinaturas'
      preLoaderRoute: typeof AdminAssinaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material': {
      id: '/material'
      path: '/material'
      fullPath: '/material'
      preLoaderRoute: typeof MaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-assinatura': {
      id: '/minha-assinatura'
      path: '/minha-assinatura'
      fullPath: '/minha-assinatura'
      preLoaderRoute: typeof MinhaAssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/osce': {
      id: '/osce'
      path: '/osce'
      fullPath: '/osce'
      preLoaderRoute: typeof OsceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-cancelado': {
      id: '/premium-cancelado'
      path: '/premium-cancelado'
      fullPath: '/premium-cancelado'
      preLoaderRoute: typeof PremiumCanceladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-pendente': {
      id: '/premium-pendente'
      path: '/premium-pendente'
      fullPath: '/premium-pendente'
      preLoaderRoute: typeof PremiumPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-sucesso': {
      id: '/premium-sucesso'
      path: '/premium-sucesso'
      fullPath: '/premium-sucesso'
      preLoaderRoute: typeof PremiumSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados': {
      id: '/simulados'
      path: '/simulados'
      fullPath: '/simulados'
      preLoaderRoute: typeof SimuladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/classificacao/processar': {
      id: '/api/public/classificacao/processar'
      path: '/api/public/classificacao/processar'
      fullPath: '/api/public/classificacao/processar'
      preLoaderRoute: typeof ApiPublicClassificacaoProcessarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/migracao-taxonomia/processar': {
      id: '/api/public/migracao-taxonomia/processar'
      path: '/api/public/migracao-taxonomia/processar'
      fullPath: '/api/public/migracao-taxonomia/processar'
      preLoaderRoute: typeof ApiPublicMigracaoTaxonomiaProcessarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reclassificacao/processar': {
      id: '/api/public/reclassificacao/processar'
      path: '/api/public/reclassificacao/processar'
      fullPath: '/api/public/reclassificacao/processar'
      preLoaderRoute: typeof ApiPublicReclassificacaoProcessarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminAssinaturasRoute: AdminAssinaturasRoute,
  AuthRoute: AuthRoute,
  CronogramaRoute: CronogramaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EquipesRoute: EquipesRoute,
  FlashcardsRoute: FlashcardsRoute,
  IaRoute: IaRoute,
  ImportarRoute: ImportarRoute,
  LigasRoute: LigasRoute,
  MaterialRoute: MaterialRoute,
  McpRoute: McpRoute,
  MinhaAssinaturaRoute: MinhaAssinaturaRoute,
  OsceRoute: OsceRoute,
  PerfilRoute: PerfilRoute,
  PremiumRoute: PremiumRoute,
  PremiumCanceladoRoute: PremiumCanceladoRoute,
  PremiumPendenteRoute: PremiumPendenteRoute,
  PremiumSucessoRoute: PremiumSucessoRoute,
  QuestoesRoute: QuestoesRoute,
  RankingRoute: RankingRoute,
  SimuladosRoute: SimuladosRoute,
  SuporteRoute: SuporteRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicClassificacaoProcessarRoute: ApiPublicClassificacaoProcessarRoute,
  ApiPublicMigracaoTaxonomiaProcessarRoute:
    ApiPublicMigracaoTaxonomiaProcessarRoute,
  ApiPublicReclassificacaoProcessarRoute:
    ApiPublicReclassificacaoProcessarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
